### ISSUE TITLE
cluster - different block values

### ISSUE THREAD

**Issue by vrfebet** [uaktags/explorer#21]
```
622526: 16645814a60898b9f4717d18f57af8110d66a02f189ecd8ee4529ff6a1ee46ea
update_tx_db finished. Updating stats.Last to set 622526
worker 10602 died
There are still 0 workers
Updating Richlist - Recieved
Updating Richlist - Balance
Getting Stats
Updating CronJob_Run
```
```
root@explorer:~/explorerV3# elicoin-cli getblockcount
623700
```
```
root@explorer:~/explorerV3# /usr/bin/nodejs scripts/sync.js index check 2>&1 | tee sync-logV3_1.txt
script launched with pid: 12437
(node:12437) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Please wait, generating a list of blocks.
Done, moving on to checking what blocks are in the DB.
There are 606966 known blocks
Update Stats Completed.
/root/explorerV3/node_modules/mongoose/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

TypeError: Cannot read property 'length' of undefined
    at clusterStart (/root/explorerV3/scripts/sync.js:143:56)
    at /root/explorerV3/scripts/sync.js:324:13
    at /root/explorerV3/lib/database.js:771:20
    at callback (/root/explorerV3/node_modules/mongoose/lib/query.js:4015:9)
    at /root/explorerV3/node_modules/mongoose/lib/query.js:4249:12
    at result (/root/explorerV3/node_modules/mongoose/node_modules/mongodb/lib/utils.js:410:17)
    at session.endSession (/root/explorerV3/node_modules/mongoose/node_modules/mongodb/lib/utils.js:398:11)
    at ClientSession.endSession (/root/explorerV3/node_modules/mongoose/node_modules/mongodb-core/lib/sessions.js:134:41)
    at executeCallback (/root/explorerV3/node_modules/mongoose/node_modules/mongodb/lib/utils.js:395:17)
    at updateCallback (/root/explorerV3/node_modules/mongoose/node_modules/mongodb/lib/operations/collection_ops.js:1413:3)
    at updateDocuments (/root/explorerV3/node_modules/mongoose/node_modules/mongodb/lib/operations/collection_ops.js:1502:62)
    at handleCallback (/root/explorerV3/node_modules/mongoose/node_modules/mongodb/lib/utils.js:128:55)
    at coll.s.topology.update (/root/explorerV3/node_modules/mongoose/node_modules/mongodb/lib/operations/collection_ops.js:1467:5)
    at /root/explorerV3/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:397:18
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
root@explorer:~/explorerV3#
```

stats.Last is 622526
real last is  623700
checking  is  606966 Update Stats Completed - but that's not true

Balance wallets, Coin Supply, (on the web) also have incorrect values

**Comment by uaktags** [comment]
stats.Last does not equal the same definition as getblockcount, so it makes sense these don't match.

sync index update, says that it counted only 606966 blocks in the database (this is definitely true).

Balance wallets/CoinSupply won't be updated/correct until you've fully synced the chain to the database

**Comment by uaktags** [comment]
Guessing this is related to #14 since this code doesn't exist in master yet.

Coin: elicoin
Closing for now, reopen if there's something specific to look in. Please remember to provide the needed info to properly track issues and any ideas/solutions for the issue.
