### ISSUE TITLE
error on first run

### ISSUE THREAD

**Issue by enginama** [uaktags/explorer#4]
/root/motion-explorer/node_modules/debug/src/node.js:132
        let val = process.env[key];
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/motion-explorer/node_modules/debug/src/index.js:9:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by uaktags** [comment]
Can you please provide more information. All I'm seeing out of this is that "debug" is failing.
Node version, npm version, os, any logs just before failure to get an idea of where this is coming in from.

**Comment by uaktags** [comment]
Closing issue for now.
