### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by minkcrypto-zz** [uaktags/explorer#48]
```[2019-07-26T11:31:27.313] [ERROR] Workers.Master - Exception is: TypeError: Cannot read property 'length' of undefined
    at /home/ubuntu/.explorer/lib/database.js:831:78
    at Request._callback (/home/ubuntu/.explorer/lib/explorer.js:223:16)
    at Request.self.callback (/home/ubuntu/.explorer/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/ubuntu/.explorer/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/.explorer/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

This happens while syncing

**Comment by minkcrypto-zz** [comment]
I think this crash happens when syncing blocks with big transactions ( maybe 100 recipient or something ), it doesn't happen with original iquidus.

**Comment by uaktags** [comment]
That doesn't quite make sense with what's happening in that code segment:

https://github.com/uaktags/explorer/blob/06d8229a97548633dd1de8b013b37b22f93c28bd/lib/database.js#L822-L831

What this is saying is that there's no such thing as "block.tx" which means that "block" itself, if it is an actual JSON object containing a block, doesn't include any transactions.

can you get it to output the block itself ``console.log(block);`` and perhaps the blockhash as well?
