### ISSUE TITLE
First run - this.options.preload.forEach error

### ISSUE THREAD

**Issue by spy0012** [uaktags/explorer#7]
Just wondered if anyone could help with this error, Clean install and running with npm start and i get the below error, i also know this is WIP but i cannot solve this issue.

`Starting cluster with pid: 9034
/var/www/vhosts/explorer/node_modules/i18next/dist/commonjs/i18next.js:234
          this.options.preload.forEach(function (l) {
                               ^
TypeError: this.options.preload.forEach is not a function
    at I18n.loadResources (/var/www/vhosts/explorer/node_modules/i18next/dist/commonjs/i18next.js:234:32)
    at setLng (/var/www/vhosts/explorer/node_modules/i18next/dist/commonjs/i18next.js:320:16)
    at I18n.changeLanguage (/var/www/vhosts/explorer/node_modules/i18next/dist/commonjs/i18next.js:326:9)
    at Timeout.load [as _onTimeout] (/var/www/vhosts/explorer/node_modules/i18next/dist/commonjs/i18next.js:178:16)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
/var/www/vhosts/explorer/node_modules/i18next/dist/commonjs/i18next.js:234
          this.options.preload.forEach(function (l) {
`
I have not changed any dependencies  just edited settings and run, as per a previous install without i18next.

any help on narrowing down the issue is appreciated - I also seen the error mentioned on another issue but i have the language change already as it was a recent download.

I know you can't reproduce it looking at your comments on the other issue, did you replicate the error, as i can't find any information on this.

Server Linux 18.04
Mongodb - 3.6.12
Nodejs - 8.10.0

**Comment by uaktags** [comment]
I might have to look to an alternative for this multilang.

What's your npm version? Going to try spinning up a VM to work with

**Comment by spy0012** [comment]
npm version is 3.5.2

Tried reverting language back to languages and it stops that error but doesn't work even then

**Comment by uaktags** [comment]
installed that vm, encountering the issue now. working through it now.

**Comment by uaktags** [comment]
F-ing stupid.
So this issue is actually a new break from the settings.js fix we had. Preload needs an array, but I removed the array when I did the variable change to language (from languages).

**Comment by spy0012** [comment]
The explorer launches as intended now, there are other issues with with sync.js not tried any of the other scripts only that one.

`root@vmi254042:/var/www/vhosts/explorer# /usr/bin/nodejs scripts/sync.js index update
script launched with pid: 5484
(node:5484) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Update Stats Completed.
/var/www/vhosts/explorer/lib/explorer.js:384
    module.exports.syncLoop(tx.vin.length, function (loop) {
                                   ^
TypeError: Cannot read property 'length' of undefined
    at Object.prepare_vin (/var/www/vhosts/explorer/lib/explorer.js:384:36)
    at /var/www/vhosts/explorer/lib/database.js:153:15
    at Request._callback (/var/www/vhosts/explorer/lib/explorer.js:122:14)
    at Request.self.callback (/var/www/vhosts/explorer/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/vhosts/explorer/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/var/www/vhosts/explorer/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`
Want me to open a new issue, this is a fresh install

**Comment by spy0012** [comment]
Works Great now as far as i can tell, there are issues with the /scripts want me to create a new issue. Issues  like masternodes.js throws an error then sync.js won't complete creating index in tmp stopping all updates.
Masternode page not showing masternodes. Let me know and i will try to compile a list of errors

**Comment by uaktags** [comment]
Yea, let's get this closed and then create a new issue. This way we can keep track of issues and fixes via commits.
Thanks
I'm using Vulc to test with in terms of masternodes so i'll go through and test. Last i remember I was making tweaks to sync and may have broke it
